### PR TITLE
Adds support for HashiCorp Vault as CA backend.

### PR DESCRIPTION
**Pull request by masstamike**

### CODE REVIEW

**Comment by Stype** [comment]
Very cool!

Needs some docs. I'll take a more in depth look through the code tomorrow or Monday. In general though, I think it makes lots of sense to have multiple CA backends. Thanks for doing this!

**Comment by masstamike** [comment]
No prob @Stype! Let me know if you'd like me to add anything as far as documentation or testing.

**Comment by myoung34** [comment]
Any updates? This is awesome

**Comment by myoung34** [comment]
any updates @masstamike @Stype ?

**Comment by masstamike** [comment]
@myoung34, I'm trying to keep this branch up to date so it can be merged in.

@Stype, have you been able to take a look and see if it's merge worthy? Let me know if there's anything else I can do.

**Comment by myoung34** [comment]
@Stype Ping. I've been in contact with others on slack but not sure what else we can  do

**Comment by Stype** [comment]
(/me emerges from hibernation)

Before merging this in, it would be great if this patch could make 'bless' the default backend, so that anyone with an existing, deployed config file can update without issues. I can add a followup commit to your branch if that's easier.

Either before or after, I'd like to refactor bless() and vault_bless() to reduce the amount of duplicated code. Just so we don't have to fix bugs twice down the road. I'm happy to do that work after merging this if you don't have time.

**Comment by masstamike** [comment]
@Stype good catch on existing deployments. I can make the update for that. I plan on making a few more improvements such as MFA support for the auth backends on Vault and support for [client-side TLS](https://www.vaultproject.io/docs/configuration/listener/tcp.html#tls_require_and_verify_client_cert) later on down the road so if you don't get to deduping before I have those PRs ready, I can work on it then.

**Comment by masstamike** [comment]
@Stype, is the most recent commit what you had in mind?

**Comment by Stype** [comment]
@masstamike I think bless_config needs to be update, so that the configuration can load without throwing and exception when those pieces are missing from blessclient.cfg.

e.g.,
```
chrissteipp@trotsky:/tmp/python-blessclient$ git checkout support_hashicorp_vault
Switched to branch 'support_hashicorp_vault'
Your branch is up-to-date with 'origin/support_hashicorp_vault'.
chrissteipp@trotsky:/tmp/python-blessclient$ python2.7
Python 2.7.14 (default, Sep 25 2017, 09:53:17) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from blessclient.bless_config import BlessConfig
>>> config_filename = '/Users/chrissteipp/lyft/blessclient/blessclient.cfg'
>>> bless_config = BlessConfig()
>>> f = open(config_filename, 'r')
>>> bless_config.parse_config_file(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "blessclient/bless_config.py", line 46, in parse_config_file
    'ca_backend': config.get('MAIN', 'ca_backend'),
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'ca_backend' in section: 'MAIN'
```

I did a local hack for testing, and added `'ca_backend': 'bless',` in DEFAULT_CONFIG, and then in parse_config_file it looks like,
```
            },
            'VAULT_CONFIG': None,
            'REGION_ALIAS': {}
        }

        if blessconfig['BLESS_CONFIG']['ca_backend'] == 'hashicorp-vault':
            blessconfig['VAULT_CONFIG'] = {
                'vault_addr': config.get('VAULT', 'vault_addr'),
                'auth_mount': config.get('VAULT', 'auth_mount'),
                'ssh_backend_mount': config.get('VAULT', 'ssh_backend_mount'),
                'ssh_backend_role': config.get('VAULT', 'ssh_backend_role')
            }
        regions = config.get('MAIN', 'region_aliases').split(",")
```

And then the config can load when those values are missing from the config file.

**Comment by masstamike** [comment]
Let me know how it looks now @Stype, and if it's easier for you to make a quick change, feel free to do so. It won't hurt my feelings.

**Comment by Stype** [comment]
This looks right. I'll try to get this fully tested soon, but I'm pretty sure this is going to be fine.

**Pull request merged**
